overrides:
  brace-expansion@<5.0.5: '>=5.0.5'
  cookie@<0.7.0: '>=0.7.0'
  picomatch@<2.3.2: '>=2.3.2'
  picomatch@>=4.0.0 <4.0.4: '>=4.0.4'
  serialize-javascript@<=7.0.2: '>=7.0.3'
  yaml@>=1.0.0 <1.10.3: '>=1.10.3'
