<script lang="ts">
	// This code is generated by Claude 3.7 Sonnet
	import { page } from '$app/state';
	import { base } from '$app/paths';

	function generateBreadcrumbs(pathname: string) {
		// base pathがある場合は除去する
		let path = pathname;
		if (base && path.startsWith(base)) {
			path = path.slice(base.length);
		}

		// 先頭と末尾のスラッシュを処理
		path = path.replace(/^\/|\/$/g, '');

		// 空のパスの場合はホームのみ
		if (!path) {
			return [{ name: 'home', path: '/' }];
		}

		// パスをセグメントに分割
		const segments = path.split('/');
		const breadcrumbs = [{ name: 'home', path: '/' }];

		// 各セグメントに対してパンくずリストを生成（括弧で囲まれたグループディレクトリを除外）
		let currentPath = '';
		for (let i = 0; i < segments.length; i++) {
			const segment = segments[i];

			// グループディレクトリ (parentheses-enclosed) は無視
			if (segment.match(/^\(.+\)$/)) {
				continue;
			}

			// 動的ルートパラメータの処理
			let displayName = segment;
			if (segment.match(/^\[.+\]$/)) {
				const paramName = segment.replace(/^\[|\]$/g, '');
				const paramValue = page.params[paramName];
				displayName = paramValue || paramName;
			}

			currentPath += `/${segment}`;
			breadcrumbs.push({
				name: decodeURIComponent(displayName),
				path: currentPath
			});
		}

		return breadcrumbs;
	}

	let breadcrumbs = $derived(generateBreadcrumbs(page.url.pathname));
</script>

<nav aria-label="Breadcrumbs">
	<ol role="list">
		{#each breadcrumbs as crumb, index}
			<li translate="no">
				{#if index < breadcrumbs.length - 1}
					<a href="{base}{crumb.path}">
						<span>{crumb.name}</span>
					</a>
					<span aria-hidden="true">/</span>
				{:else}
					<span class="current" aria-current="page">
						{crumb.name}
					</span>
				{/if}
			</li>
		{/each}
	</ol>
</nav>

<style lang="scss">
	nav {
		writing-mode: vertical-rl;
		position: fixed;
		right: 0.25rem;
		overflow-wrap: normal;
		line-height: 1.2;
		ol {
			color: var(--bluegrey-40);
			font-size: round(up, 0.8em, 1px);
			margin-block: 0;
			padding-inline-start: 0;
			display: flex;
			column-gap: 0.1rem; // Temporary fix

			li {
				display: flex;
				column-gap: 0.1rem;
			}
		}
	}
</style>
