name: Prettier and ESLint Validation

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  prettier-eslint-validation:
    name: Prettier and ESLint Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Validation
        id: validation
        continue-on-error: true
        run: npm run lint > output.log 2>&1

      - name: Summary
        if: always()
        run: |
          if [ "${{ steps.validation.outcome }}" = "success" ]; then
            echo "✅ Prettier and ESLint validation passed."
          else
            echo "❌ Prettier and ESLint validation failed."
            echo "---- Output ----"
            cat output.log
            exit 1
          fi
