name: Prettier Format Validation

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  prettier-check:
    name: Prettier Format Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Validate Prettier formatting
        id: prettier
        continue-on-error: true
        run: |
          echo "Running Prettier check on source files..."
          npx prettier --cache --check "src/**/*.{js,ts,svelte,css,scss,json,html}"

      - name: Format check summary
        if: always()
        run: |
          if grep -q "Code style issues found" prettier-check.log; then
            echo "❌ Some files are not properly formatted."
            echo "Unformatted files:"
            # フォーマットされていないファイル名を表示
            grep -E 'src/.*\.(js|ts|svelte|css|scss|json|html)' prettier-check.log
            exit 1
          else
            echo "✅ All files are properly formatted according to Prettier rules."
          fi
